package com.example.carrierlookup.ui

import androidx.compose.runtime.staticCompositionLocalOf
import com.example.carrierlookup.data.LineType
import com.example.carrierlookup.data.SpamLevel
import com.example.carrierlookup.data.SpamReason

/** Tutti i testi dell'interfaccia, in una lingua. */
class Strings(
    val tabSearch: String,
    val tabHistory: String,
    val tabSettings: String,
    val greetMorning: String,
    val greetAfternoon: String,
    val greetEvening: String,
    val greetNight: String,
    val subtitle: String,
    val signInGoogle: String,
    val signingIn: String,
    val country: String,
    val otherPrefix: String,
    val numberHint: String,
    val search: String,
    val paste: String,
    val contacts: String,
    val clear: String,
    val unknownCarrier: String,
    val validNumber: String,
    val invalidNumber: String,
    val copyNumber: String,
    val rowNumber: String,
    val rowCountry: String,
    val rowLineType: String,
    val rowSource: String,
    val call: String,
    val sendSms: String,
    val creditsUsed: String,
    val today: String,
    val thisMonth: String,
    val lastSearch: String,
    val none: String,
    val yesterday: String,
    val creditsInfo: String,
    val todayCount: String,
    val noSearchToday: String,
    val last7Days: String,
    val close: String,
    val chooseCountry: String,
    val otherPrefixHint: String,
    val usePrefix: String,
    val historyTitle: String,
    val clearAll: String,
    val noHistory: String,
    val settingsTitle: String,
    val account: String,
    val notSignedIn: String,
    val signOut: String,
    val infoAndCredits: String,
    val appearance: String,
    val darkMode: String,
    val language: String,
    val infoTitle: String,
    val infoMade: String,
    val infoSources: String,
    val infoPortability: String,
    val madeBy: String,
    val lineMobile: String,
    val lineFixed: String,
    val lineFixedOrMobile: String,
    val lineVoip: String,
    val lineTollFree: String,
    val linePremium: String,
    val lineOther: String,
    val lineUnknown: String,
    val menu: String,
    val offersTitle: String,
    val offersNote: String,
    val offersOpen: String,
    val offersTagline: String,
    val spamRisk: String,
    val spamLow: String,
    val spamMedium: String,
    val spamHigh: String,
    val reasonBlocklist: String,
    val reasonPremium: String,
    val reasonVoip: String,
    val reasonInvalid: String,
    val reasonWangiri: String,
    val noSignals: String,
    val blockAdd: String,
    val blockRemove: String,
    val spamTitle: String,
    val callFilter: String,
    val filterActive: String,
    val filterInactive: String,
    val filterActivate: String,
    val filterUnavailable: String,
    val filterExplain: String,
    val blockSuspected: String,
    val blockSuspectedHint: String,
    val blockedCalls: String,
    val blocklistTitle: String,
    val blocklistEmpty: String,
    val addNumberHint: String,
    val add: String,
    val spamLimits: String,
    val invalidNumberInput: String,
    val donateTitle: String,
    val donateHint: String,
    val donateButton: String,
    val donateNotSet: String
) {
    fun greeting(hour: Int): String = when (hour) {
        in 5..11 -> greetMorning
        in 12..17 -> greetAfternoon
        in 18..21 -> greetEvening
        else -> greetNight
    }

    fun level(l: SpamLevel): String = when (l) {
        SpamLevel.LOW -> spamLow
        SpamLevel.MEDIUM -> spamMedium
        SpamLevel.HIGH -> spamHigh
    }

    fun reason(r: SpamReason): String = when (r) {
        SpamReason.BLOCKLIST -> reasonBlocklist
        SpamReason.PREMIUM -> reasonPremium
        SpamReason.VOIP -> reasonVoip
        SpamReason.INVALID -> reasonInvalid
        SpamReason.WANGIRI_PREFIX -> reasonWangiri
    }

    fun lineType(t: LineType): String = when (t) {
        LineType.MOBILE -> lineMobile
        LineType.FIXED_LINE -> lineFixed
        LineType.FIXED_OR_MOBILE -> lineFixedOrMobile
        LineType.VOIP -> lineVoip
        LineType.TOLL_FREE -> lineTollFree
        LineType.PREMIUM_RATE -> linePremium
        LineType.OTHER -> lineOther
        LineType.UNKNOWN -> lineUnknown
    }
}

val StringsIt = Strings(
    tabSearch = "Ricerca",
    tabHistory = "Cronologia",
    tabSettings = "Impostazioni",
    greetMorning = "Buongiorno",
    greetAfternoon = "Buon pomeriggio",
    greetEvening = "Buonasera",
    greetNight = "Buona notte",
    subtitle = "Scopri l'operatore di un numero",
    signInGoogle = "Accedi con Google",
    signingIn = "Accesso in corso…",
    country = "Paese",
    otherPrefix = "Altro prefisso",
    numberHint = "Numero di telefono",
    search = "Cerca",
    paste = "Incolla",
    contacts = "Contatti",
    clear = "Cancella",
    unknownCarrier = "Operatore sconosciuto",
    validNumber = "Numero valido",
    invalidNumber = "Numero non valido",
    copyNumber = "Copia numero",
    rowNumber = "Numero",
    rowCountry = "Paese",
    rowLineType = "Tipo di linea",
    rowSource = "Fonte",
    call = "Chiama",
    sendSms = "Invia SMS",
    creditsUsed = "Crediti usati",
    today = "Oggi",
    thisMonth = "Questo mese",
    lastSearch = "Ultima ricerca",
    none = "nessuna",
    yesterday = "ieri",
    creditsInfo = "Ogni ricerca online usa 1 credito. Le ricerche offline sono gratis.",
    todayCount = "Oggi",
    noSearchToday = "Nessuna ricerca oggi.",
    last7Days = "Ultimi 7 giorni",
    close = "Chiudi",
    chooseCountry = "Scegli il paese",
    otherPrefixHint = "Altro prefisso (es. 39)",
    usePrefix = "Usa",
    historyTitle = "Cronologia",
    clearAll = "Cancella tutto",
    noHistory = "Nessuna ricerca ancora.",
    settingsTitle = "Impostazioni",
    account = "Account",
    notSignedIn = "Non hai fatto l'accesso",
    signOut = "Esci",
    infoAndCredits = "Informazioni e crediti",
    appearance = "Aspetto",
    darkMode = "Tema scuro",
    language = "Lingua",
    infoTitle = "Informazioni",
    infoMade = "Fatta con ❤️ da Clacson.",
    infoSources = "Ricerca online: omkar.cloud (usa 1 credito). Ricerca offline: libphonenumber di Google, gratuita.",
    infoPortability = "Con la portabilità del numero (MNP) l'operatore indicato può non essere quello attuale.",
    madeBy = "Fatta da Clacson",
    lineMobile = "Mobile",
    lineFixed = "Linea fissa",
    lineFixedOrMobile = "Fisso o mobile",
    lineVoip = "VoIP",
    lineTollFree = "Numero verde",
    linePremium = "Tariffa premium",
    lineOther = "Altro",
    lineUnknown = "Sconosciuto",
    menu = "Menu",
    offersTitle = "Offerte operatori",
    offersNote = "Gli operatori di rete mobile (MNO) italiani. Prezzi e promozioni cambiano spesso: le offerte aggiornate le trovi sempre sul sito ufficiale.",
    offersOpen = "Vedi le offerte",
    offersTagline = "Operatore di rete mobile",
    spamRisk = "Rischio spam",
    spamLow = "Basso",
    spamMedium = "Medio",
    spamHigh = "Alto",
    reasonBlocklist = "è nella tua lista nera",
    reasonPremium = "numero a tariffa premium",
    reasonVoip = "linea VoIP (usata spesso per telefonate commerciali)",
    reasonInvalid = "numero non valido",
    reasonWangiri = "prefisso spesso usato per chiamate-truffa (Wangiri)",
    noSignals = "Nessun segnale sospetto",
    blockAdd = "Aggiungi alla lista nera",
    blockRemove = "Rimuovi dalla lista nera",
    spamTitle = "Anti spam",
    callFilter = "Filtro chiamate",
    filterActive = "Attivo",
    filterInactive = "Non attivo",
    filterActivate = "Attiva il filtro",
    filterUnavailable = "Non disponibile su questo telefono",
    filterExplain = "Per bloccare le chiamate, l'app deve diventare l'app anti spam di Android. Il telefono ti chiederà conferma.",
    blockSuspected = "Blocca anche i numeri sospetti",
    blockSuspectedHint = "Numeri a tariffa premium e prefissi usati per le chiamate-truffa",
    blockedCalls = "Chiamate bloccate",
    blocklistTitle = "Lista nera",
    blocklistEmpty = "Nessun numero bloccato.",
    addNumberHint = "Numero da bloccare (es. +39 333…)",
    add = "Aggiungi",
    spamLimits = "Non esiste un elenco mondiale di spammer: il giudizio si basa su regole (tipo di numero e prefisso) e sulla tua lista nera.",
    invalidNumberInput = "Numero non valido",
    donateTitle = "Offrimi un caffè",
    donateHint = "Se l'app ti è utile, puoi sostenerne lo sviluppo con una donazione libera.",
    donateButton = "Dona",
    donateNotSet = "Link per le donazioni non ancora configurato."
)

val StringsEn = Strings(
    tabSearch = "Search",
    tabHistory = "History",
    tabSettings = "Settings",
    greetMorning = "Good morning",
    greetAfternoon = "Good afternoon",
    greetEvening = "Good evening",
    greetNight = "Good night",
    subtitle = "Find the carrier of a number",
    signInGoogle = "Sign in with Google",
    signingIn = "Signing in…",
    country = "Country",
    otherPrefix = "Other prefix",
    numberHint = "Phone number",
    search = "Search",
    paste = "Paste",
    contacts = "Contacts",
    clear = "Clear",
    unknownCarrier = "Unknown carrier",
    validNumber = "Valid number",
    invalidNumber = "Invalid number",
    copyNumber = "Copy number",
    rowNumber = "Number",
    rowCountry = "Country",
    rowLineType = "Line type",
    rowSource = "Source",
    call = "Call",
    sendSms = "Send SMS",
    creditsUsed = "Credits used",
    today = "Today",
    thisMonth = "This month",
    lastSearch = "Last search",
    none = "none",
    yesterday = "yesterday",
    creditsInfo = "Each online search uses 1 credit. Offline searches are free.",
    todayCount = "Today",
    noSearchToday = "No searches today.",
    last7Days = "Last 7 days",
    close = "Close",
    chooseCountry = "Choose country",
    otherPrefixHint = "Other prefix (e.g. 39)",
    usePrefix = "Use",
    historyTitle = "History",
    clearAll = "Clear all",
    noHistory = "No searches yet.",
    settingsTitle = "Settings",
    account = "Account",
    notSignedIn = "You are not signed in",
    signOut = "Sign out",
    infoAndCredits = "About and credits",
    appearance = "Appearance",
    darkMode = "Dark theme",
    language = "Language",
    infoTitle = "About",
    infoMade = "Made with ❤️ by Clacson.",
    infoSources = "Online search: omkar.cloud (uses 1 credit). Offline search: Google's libphonenumber, free.",
    infoPortability = "With number portability (MNP) the carrier shown may not be the current one.",
    madeBy = "Made by Clacson",
    lineMobile = "Mobile",
    lineFixed = "Landline",
    lineFixedOrMobile = "Fixed or mobile",
    lineVoip = "VoIP",
    lineTollFree = "Toll-free",
    linePremium = "Premium rate",
    lineOther = "Other",
    lineUnknown = "Unknown",
    menu = "Menu",
    offersTitle = "Carrier offers",
    offersNote = "The Italian mobile network operators (MNOs). Prices and promotions change often: you will always find current offers on the official website.",
    offersOpen = "See offers",
    offersTagline = "Mobile network operator",
    spamRisk = "Spam risk",
    spamLow = "Low",
    spamMedium = "Medium",
    spamHigh = "High",
    reasonBlocklist = "it is in your blocklist",
    reasonPremium = "premium-rate number",
    reasonVoip = "VoIP line (often used for sales calls)",
    reasonInvalid = "invalid number",
    reasonWangiri = "prefix often used in scam calls (Wangiri)",
    noSignals = "No suspicious signs",
    blockAdd = "Add to blocklist",
    blockRemove = "Remove from blocklist",
    spamTitle = "Anti-spam",
    callFilter = "Call filter",
    filterActive = "Active",
    filterInactive = "Not active",
    filterActivate = "Turn on the filter",
    filterUnavailable = "Not available on this phone",
    filterExplain = "To block calls, the app must become Android's call screening app. Your phone will ask you to confirm.",
    blockSuspected = "Also block suspicious numbers",
    blockSuspectedHint = "Premium-rate numbers and prefixes used in scam calls",
    blockedCalls = "Blocked calls",
    blocklistTitle = "Blocklist",
    blocklistEmpty = "No blocked numbers.",
    addNumberHint = "Number to block (e.g. +39 333…)",
    add = "Add",
    spamLimits = "There is no worldwide list of spammers: the verdict relies on rules (number type and prefix) and on your blocklist.",
    invalidNumberInput = "Invalid number",
    donateTitle = "Buy me a coffee",
    donateHint = "If the app is useful to you, you can support its development with a free donation.",
    donateButton = "Donate",
    donateNotSet = "Donation link not set up yet."
)

val LocalStrings = staticCompositionLocalOf { StringsIt }

fun stringsFor(language: String): Strings = if (language == "en") StringsEn else StringsIt
